""" pbgui_ui.py --

 UI generated by GUI Builder Build 146 on 2011-08-02 17:14:49 from:
    /media/lisa/Hubi/code/testgui/pbgui.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Pbgui(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._frame_9 = Tkinter.Frame(root,
        )
        self._frame_6 = Tkinter.Frame(root,
        )
        self._frame_10 = Tkinter.Frame(root,
        )
        self._frame_1 = Tkinter.Frame(self._frame_9,
        )
        self._frame_2 = Tkinter.Frame(self._frame_9,
        )
        self._frame_3 = Tkinter.Frame(self._frame_9,
        )
        self._frame_4 = Tkinter.Frame(self._frame_3,
        )
        self._frame_5 = Tkinter.Frame(self._frame_3,
        )
        self._frame_7 = Tkinter.Frame(self._frame_4,
        )
        self._frame_8 = Tkinter.Frame(self._frame_4,
        )
        self._sclModules = Tkinter.Scrollbar(self._frame_1,
            borderwidth = 1,
        )
        self._lsModules = Tkinter.Listbox(self._frame_1,
            exportselection = 0,
            font = "helvetica 9",
            height = 5,
            selectmode = "single",
            width = 25,
        )
        self._sclNodes = Tkinter.Scrollbar(self._frame_2,
            borderwidth = 1,
        )
        self._lsNodes = Tkinter.Listbox(self._frame_2,
            exportselection = 0,
            font = "helvetica 9",
            height = 7,
            selectmode = "single",
            width = 25,
        )
        self._sclListconfig = Tkinter.Scrollbar(self._frame_7,
            borderwidth = 1,
        )
        self._lsListconfig = Tkinter.Listbox(self._frame_7,
            exportselection = 0,
            font = "helvetica 9",
            height = 7,
            width = 0,
        )
        self._txTextconfig = Tkinter.Text(self._frame_8,
            exportselection = 0,
            font = "helvetica 9",
            height = 7,
            width = 0,
        )
        self._sclTextconfig = Tkinter.Scrollbar(self._frame_8,
            borderwidth = 1,
        )
        self._labTextconfig = Tkinter.Label(self._frame_4,
            text = "text config",
        )
        self._labListconfig = Tkinter.Label(self._frame_4,
            text = "list config",
        )
        self._butReset = Tkinter.Button(self._frame_5,
            text = "no function",
            width = 10,
        )
        self._panedwindow_1 = Tkinter.PanedWindow(self._frame_5,
            height = 0,
            width = 0,
        )
        self._labModules = Tkinter.Label(self._frame_9,
            anchor = "nw",
            font = "helvetica 9",
            justify = "left",
            text = "current module information",
        )
        self._labNodes = Tkinter.Label(self._frame_9,
            anchor = "nw",
            font = "helvetica 9",
            justify = "left",
            text = "current node information",
        )
        self._labConfig = Tkinter.Label(self._frame_9,
            anchor = "nw",
            font = "helvetica 9",
            justify = "left",
            text = "current configuration",
        )
        self._panedwindow_2 = Tkinter.PanedWindow(self._frame_6,
            height = 0,
            width = 0,
        )
        self._butLoadfile = Tkinter.Button(self._frame_6,
            text = "load config",
            width = 10,
        )
        self._butSavefile = Tkinter.Button(self._frame_6,
            text = "save as",
            width = 10,
        )
        self._butOk = Tkinter.Button(self._frame_6,
            text = "ok",
            width = 10,
        )
        self._butCancel = Tkinter.Button(self._frame_6,
            text = "cancel",
            width = 10,
        )
        self._label_7 = Tkinter.Label(self._frame_10,
            text = "status:",
        )
        self._labStatus = Tkinter.Label(self._frame_10,
            anchor = "w",
            text = "started...",
        )
        self._butApply = Tkinter.Button(self._frame_5,
            text = "apply",
            width = 10,
        )

        # widget commands

        self._sclModules.configure(
            command = self._sclModules_command
        )
        self._lsModules.configure(
            xscrollcommand = self._lsModules_xscrollcommand
        )
        self._lsModules.configure(
            yscrollcommand = self._sclModules.set
        )
        self._sclNodes.configure(
            command = self._sclNodes_command
        )
        self._lsNodes.configure(
            xscrollcommand = self._lsNodes_xscrollcommand
        )
        self._lsNodes.configure(
            yscrollcommand = self._sclNodes.set
        )
        self._sclListconfig.configure(
            command = self._sclListconfig_command
        )
        self._lsListconfig.configure(
            xscrollcommand = self._lsListconfig_xscrollcommand
        )
        self._lsListconfig.configure(
            yscrollcommand = self._sclListconfig.set
        )
        self._txTextconfig.configure(
            xscrollcommand = self._txTextconfig_xscrollcommand
        )
        self._txTextconfig.configure(
            yscrollcommand = self._sclTextconfig.set
        )
        self._sclTextconfig.configure(
            command = self._sclTextconfig_command
        )
        self._butReset.configure(
            command = self._butReset_command
        )
        self._butLoadfile.configure(
            command = self._butLoadfile_command
        )
        self._butSavefile.configure(
            command = self._butSavefile_command
        )
        self._butOk.configure(
            command = self._butOk_command
        )
        self._butCancel.configure(
            command = self._butCancel_command
        )
        self._butApply.configure(
            command = self._butApply_command
        )


        # Geometry Management
        self._frame_9.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_6.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_10.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_1.grid(
            in_    = self._frame_9,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_2.grid(
            in_    = self._frame_9,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_3.grid(
            in_    = self._frame_9,
            column = 2,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_4.grid(
            in_    = self._frame_3,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_5.grid(
            in_    = self._frame_3,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_7.grid(
            in_    = self._frame_4,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_8.grid(
            in_    = self._frame_4,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._sclModules.grid(
            in_    = self._frame_1,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsw"
        )
        self._lsModules.grid(
            in_    = self._frame_1,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._sclNodes.grid(
            in_    = self._frame_2,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsw"
        )
        self._lsNodes.grid(
            in_    = self._frame_2,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._sclListconfig.grid(
            in_    = self._frame_7,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsw"
        )
        self._lsListconfig.grid(
            in_    = self._frame_7,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._txTextconfig.grid(
            in_    = self._frame_8,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._sclTextconfig.grid(
            in_    = self._frame_8,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsw"
        )
        self._labTextconfig.grid(
            in_    = self._frame_4,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "sew"
        )
        self._labListconfig.grid(
            in_    = self._frame_4,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "sew"
        )
        self._butReset.grid(
            in_    = self._frame_5,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._panedwindow_1.grid(
            in_    = self._frame_5,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._labModules.grid(
            in_    = self._frame_9,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )
        self._labNodes.grid(
            in_    = self._frame_9,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )
        self._labConfig.grid(
            in_    = self._frame_9,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )
        self._panedwindow_2.grid(
            in_    = self._frame_6,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._butLoadfile.grid(
            in_    = self._frame_6,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butSavefile.grid(
            in_    = self._frame_6,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butOk.grid(
            in_    = self._frame_6,
            column = 4,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butCancel.grid(
            in_    = self._frame_6,
            column = 5,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_7.grid(
            in_    = self._frame_10,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "w"
        )
        self._labStatus.grid(
            in_    = self._frame_10,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )
        self._butApply.grid(
            in_    = self._frame_5,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 29, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 33, pad = 0)
        root.grid_columnconfigure(1, weight = 1, minsize = 493, pad = 0)
        self._frame_1.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_1.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_1.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_10.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_10.grid_columnconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_10.grid_columnconfigure(2, weight = 1, minsize = 40, pad = 0)
        self._frame_2.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_2.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_2.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_3.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_3.grid_rowconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_3.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_4.grid_rowconfigure(1, weight = 0, minsize = 21, pad = 0)
        self._frame_4.grid_rowconfigure(2, weight = 1, minsize = 161, pad = 0)
        self._frame_4.grid_columnconfigure(1, weight = 1, minsize = 2, pad = 0)
        self._frame_4.grid_columnconfigure(2, weight = 1, minsize = 40, pad = 0)
        self._frame_5.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_5.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_5.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)
        self._frame_6.grid_rowconfigure(1, weight = 0, minsize = 15, pad = 0)
        self._frame_6.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_6.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_6.grid_columnconfigure(3, weight = 1, minsize = 40, pad = 0)
        self._frame_6.grid_columnconfigure(4, weight = 0, minsize = 40, pad = 0)
        self._frame_6.grid_columnconfigure(5, weight = 0, minsize = 40, pad = 0)
        self._frame_7.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_7.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_7.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_8.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_8.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_8.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_9.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_9.grid_rowconfigure(2, weight = 1, minsize = 40, pad = 0)
        self._frame_9.grid_rowconfigure(3, weight = 1, minsize = 40, pad = 0)
        self._frame_9.grid_columnconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_9.grid_columnconfigure(2, weight = 1, minsize = 2, pad = 0)


